name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      matrix:
        toolchain:
          [
            { arch: aarch64-apple-darwin, name: silicon },
            { arch: x86_64-apple-darwin, name: intel },
          ]
    name: Build ${{ matrix.toolchain.name }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.toolchain.arch }}
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.toolchain.arch }}
      - name: Test
        run: cargo test --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target ${{ matrix.toolchain.arch }}
      - run: |
          mkdir output && mv target/${{ matrix.toolchain.arch }}/release/tmbliss output/ && \
          chmod +x output/tmbliss && mv LICENCE.txt output/ && mv output ${{ matrix.toolchain.name }}
      - run: zip -qq -r ${{ matrix.toolchain.name }}.zip ${{ matrix.toolchain.name }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.toolchain.name }}
          path: ${{ matrix.toolchain.name }}.zip
  release:
    name: Make release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: ~/artifacts
      - run: mv ~/artifacts/**/* ./
      - name: "Create Release"
        uses: softprops/action-gh-release@78c309ef59fdb9557cd6574f2e0be552936ed728
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            silicon.zip
            intel.zip
